package com.CS516DE.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "order")
public class Order {

    @DynamoDBHashKey(attributeName = "orderId")
    @DynamoDBAutoGeneratedKey
    private String orderId;
    @DynamoDBAttribute(attributeName = "buyerId")
    private String buyerId;

    @DynamoDBAttribute(attributeName = "orderItems")
    private List<OrderItem> orderItems;

    @DynamoDBAttribute(attributeName = "shippingAddressId")
    private String shippingAddressId;
    @DynamoDBAttribute(attributeName = "paymentId")
    private String paymentId;

    public Order(String buyerId, List<OrderItem> orderItems, String shippingAddressId, String paymentId) {
        this.buyerId = buyerId;
        this.orderItems = orderItems;
        this.shippingAddressId = shippingAddressId;
        this.paymentId = paymentId;
    }
}
